import About from "../../Pages/About/About"
import Footer from "../../Pages/Footer/Footer"
import Home from "../../Pages/Home/Home"
import Login from "../../Pages/Login/Login"
import Navber from "../../Pages/Navber/Navber"
import PostQuestions from "../../Pages/PostQuestions/PostQuestions"
import Questions from "../../Pages/Questions/Questions"
import QuestionsAns from "../../Pages/QuestionsAns/QuestionsAns"
import Signup from "../../Pages/Signup/Signup"
import UserAccount from "../../Pages/UserAccount/UserAccount"
import UserQuestions from "../../Pages/UserQuestions/UserQuestions"
import UserAns from "../../Pages/UserAns/UserAns"
import ChangePassword from "../../Pages/ChangePassword/ChangePassword"
import ForgotPassword from "../../Pages/ForgotPassword/ForgotPassword"
import AdminQuestions from "../../Pages/AdminQuestions/AdminQuestions"
import AdminQuestionsAns from "../../Pages/AdminQuestionsAns/AdminQuestionsAns"
import AdminUserAccounts from "../../Pages/AdminUserAccounts/AdminUserAccounts"


export {About, Footer, Home, Login, Navber, PostQuestions, Questions, QuestionsAns, Signup, UserAccount, UserQuestions, UserAns, ChangePassword, ForgotPassword, AdminQuestions, AdminUserAccounts, AdminQuestionsAns}